// components/scheduling/WeekCalendar.tsx
"use client";
import { useMemo,useState,type DragEvent,type MouseEvent,type PointerEvent } from "react";
import { GripHorizontal,LoaderCircle,Plus,Trash2,X } from "lucide-react";
import { Modal } from "@/components/ui/Modal";
import type { AppointmentDayNote,CalendarAppointment } from "@/types/scheduling";
const START_HOUR=7,END_HOUR=20,HOUR_HEIGHT=72,CALENDAR_HEIGHT=(END_HOUR-START_HOUR)*HOUR_HEIGHT,MIN_EVENT_HEIGHT=34,TZ="America/Sao_Paulo";
type Props={weekDays:Date[];appointments:CalendarAppointment[];notes:AppointmentDayNote[];selectedAppointmentId:string|null;loading:boolean;onSelectAppointment:(a:CalendarAppointment)=>void;onMoveAppointment:(a:CalendarAppointment,s:string,e:string)=>Promise<void>;onResizeAppointment:(a:CalendarAppointment,e:string)=>Promise<void>;onDeleteAppointment:(a:CalendarAppointment)=>Promise<void>;onAddNote:(d:string)=>Promise<void>;onEditNote:(n:AppointmentDayNote)=>Promise<void>;onDeleteNote:(n:AppointmentDayNote)=>Promise<void>};
type Confirm={title:string;description:string;confirmLabel:string;danger?:boolean;action:()=>Promise<void>};
export default function WeekCalendar(p:Props){
 const [resize,setResize]=useState<{id:string;end:string}|null>(null),[hovered,setHovered]=useState<string|null>(null),[cursorGuide,setCursorGuide]=useState<{dayKey:string;minutes:number}|null>(null),[confirm,setConfirm]=useState<Confirm|null>(null),[confirming,setConfirming]=useState(false),[confirmError,setConfirmError]=useState<string|null>(null);
 const byDay=useMemo(()=>{const m=new Map<string,CalendarAppointment[]>();p.appointments.forEach(a=>{const k=dateKeyIso(a.starts_at),x=m.get(k)??[];x.push(a);m.set(k,x)});m.forEach(x=>x.sort((a,b)=>+new Date(a.starts_at)-+new Date(b.starts_at)));return m},[p.appointments]);
 const notesByDay=useMemo(()=>{const m=new Map<string,AppointmentDayNote[]>();p.notes.forEach(n=>m.set(n.note_date,[...(m.get(n.note_date)??[]),n]));return m},[p.notes]);
 function ask(c:Confirm){setConfirmError(null);setConfirm(c)} async function runConfirm(){if(!confirm)return;setConfirming(true);setConfirmError(null);try{await confirm.action();setConfirm(null)}catch(e){setConfirmError(e instanceof Error?e.message:"Não foi possível concluir a ação.")}finally{setConfirming(false)}}
 function beginResize(ev:PointerEvent<HTMLButtonElement>,a:CalendarAppointment){ev.preventDefault();ev.stopPropagation();const y=ev.clientY,original=+new Date(a.ends_at);let latest=original;function move(e:globalThis.PointerEvent){const delta=Math.round((((e.clientY-y)/HOUR_HEIGHT)*60)/15)*15;latest=Math.max(original+delta*60000,+new Date(a.starts_at)+15*60000);setResize({id:a.id,end:new Date(latest).toISOString()})}function up(){window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);setResize(null);if(latest===original)return;const end=new Date(latest).toISOString();ask({title:"Alterar duração?",description:`Confirmar nova duração até ${time(end)}?`,confirmLabel:"Confirmar",action:()=>p.onResizeAppointment(a,end)})}window.addEventListener("pointermove",move);window.addEventListener("pointerup",up,{once:true})}
 function drop(ev:DragEvent<HTMLDivElement>,day:Date){ev.preventDefault();const a=p.appointments.find(x=>x.id===ev.dataTransfer.getData("appointment-id"));if(!a)return;const r=ev.currentTarget.getBoundingClientRect(),raw=START_HOUR*60+((ev.clientY-r.top)/HOUR_HEIGHT)*60,start=Math.min(Math.max(Math.round(raw/15)*15,START_HOUR*60),END_HOUR*60-15),duration=+new Date(a.ends_at)-+new Date(a.starts_at),s=build(day,start),e=new Date(+new Date(s)+duration).toISOString();ask({title:"Mover agendamento?",description:`Mover ${a.patient_name} para ${dayLabel(day)} às ${time(s)}?`,confirmLabel:"Mover",action:()=>p.onMoveAppointment(a,s,e)})}
 function updateCursorGuide(ev:MouseEvent<HTMLDivElement>,dayKey:string){const r=ev.currentTarget.getBoundingClientRect(),raw=START_HOUR*60+((ev.clientY-r.top)/HOUR_HEIGHT)*60,snapped=Math.min(Math.max(Math.round(raw/15)*15,START_HOUR*60),END_HOUR*60);setCursorGuide({dayKey,minutes:snapped})}
 return <>
 <div className="min-h-0 flex-1 overflow-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="min-w-[1180px]">
  <div className="sticky top-0 z-40 grid grid-cols-[72px_repeat(7,minmax(150px,1fr))] border-b border-slate-200 bg-white"><div className="border-r border-slate-200 bg-slate-50"/>{p.weekDays.map(d=>{const k=formatLocalDateKey(d),today=k===formatLocalDateKey(new Date());return <div key={k} className={`border-r border-slate-200 px-3 py-3 text-center last:border-r-0 ${today?"bg-brand-soft/35":""}`}><div className="text-xs font-bold uppercase tracking-wide text-slate-400">{new Intl.DateTimeFormat("pt-BR",{weekday:"short"}).format(d).replace(".","")}</div><div className={`mt-1 text-sm font-bold ${today?"text-brand":"text-slate-800"}`}>{new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit"}).format(d)}</div></div>})}</div>
  <div className="grid grid-cols-[72px_repeat(7,minmax(150px,1fr))] border-b border-slate-200 bg-slate-50/60"><div className="border-r border-slate-200 px-2 py-3 text-center text-[11px] font-bold uppercase text-slate-400">Notas</div>{p.weekDays.map(d=>{const k=formatLocalDateKey(d);return <div key={k} className="group/day min-h-16 border-r border-slate-200 p-2 last:border-r-0"><div className="flex flex-wrap gap-1.5">{(notesByDay.get(k)??[]).map(n=><div key={n.id} className="group/note relative max-w-full"><button type="button" onClick={()=>void p.onEditNote(n)} className="max-w-full cursor-pointer truncate rounded-lg px-2 py-1 pr-6 text-left text-[11px] font-semibold text-white shadow-sm" style={{backgroundColor:n.color}}>{n.text}</button><button type="button" onClick={()=>void p.onDeleteNote(n)} className="absolute right-1 top-1/2 flex h-4 w-4 -translate-y-1/2 cursor-pointer items-center justify-center rounded text-white opacity-0 hover:bg-black/15 group-hover/note:opacity-100"><X size={11}/></button></div>)}<button type="button" onClick={()=>void p.onAddNote(k)} className="flex h-6 w-6 cursor-pointer items-center justify-center rounded-lg border border-dashed border-slate-300 text-slate-400 opacity-50 hover:border-brand hover:bg-brand-soft hover:text-brand group-hover/day:opacity-100"><Plus size={13}/></button></div></div>})}</div>
  <div className="relative isolate z-0 grid grid-cols-[72px_repeat(7,minmax(150px,1fr))]">{cursorGuide&&<div className="pointer-events-none absolute left-0 right-0 z-[95] border-t border-dashed border-slate-500/30" style={{top:((cursorGuide.minutes-START_HOUR*60)/60)*HOUR_HEIGHT}}><span className="absolute left-2 top-0 flex w-14 -translate-y-1/2 items-center justify-center rounded-md border border-slate-200 bg-white/95 px-1.5 py-0.5 text-[10px] font-bold tabular-nums text-slate-500 shadow-sm">{minuteLabel(cursorGuide.minutes)}</span></div>}<TimeAxis/>{p.weekDays.map(day=>{const key=formatLocalDateKey(day),items=byDay.get(key)??[];return <div key={key} className="relative border-r border-slate-200 last:border-r-0" style={{height:CALENDAR_HEIGHT,backgroundImage:`repeating-linear-gradient(to bottom,transparent 0,transparent ${HOUR_HEIGHT/2-1}px,rgb(226 232 240 / .72) ${HOUR_HEIGHT/2}px,transparent ${HOUR_HEIGHT/2+1}px)`}} onMouseMove={e=>updateCursorGuide(e,key)} onMouseLeave={()=>setCursorGuide(current=>current?.dayKey===key?null:current)} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,day)}>{items.map(a=>{const end=resize?.id===a.id?resize.end:a.ends_at,startM=minutes(a.starts_at),endM=minutes(end),top=((startM-START_HOUR*60)/60)*HOUR_HEIGHT,height=Math.max(((endM-startM)/60)*HOUR_HEIGHT,MIN_EVENT_HEIGHT),overlap=overlapIndex(a,items),selected=p.selectedAppointmentId===a.id,isHover=hovered===a.id;return <div key={a.id} draggable onDragStart={e=>{e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("appointment-id",a.id)}} onMouseEnter={()=>setHovered(a.id)} onMouseLeave={()=>setHovered(x=>x===a.id?null:x)} onClick={()=>p.onSelectAppointment(a)} className={`group absolute cursor-grab overflow-hidden rounded-lg border border-white/70 px-2 py-1.5 text-white shadow-sm transition hover:brightness-95 hover:shadow-xl active:cursor-grabbing ${selected?"ring-2 ring-slate-950/20":""}`} style={{top:Math.max(0,top),height,left:4+overlap*9,right:4,zIndex:isHover?90:selected?35:5+overlap,backgroundColor:a.doctor?.color??"#7c3aed"}}>
    <button type="button" onClick={e=>{e.stopPropagation();ask({title:"Excluir agendamento?",description:`O agendamento de ${a.patient_name} será removido permanentemente.`,confirmLabel:"Excluir",danger:true,action:()=>p.onDeleteAppointment(a)})}} className="absolute right-1 top-1 flex h-5 w-5 cursor-pointer items-center justify-center rounded bg-black/10 opacity-0 hover:bg-black/20 group-hover:opacity-100"><Trash2 size={12}/></button><div className="pr-5 text-[10px] font-bold leading-tight opacity-90">{time(a.starts_at)}–{time(end)}</div><div className="mt-0.5 truncate text-[11px] font-bold leading-tight">{a.doctor?.name??"Sem médico"}</div><div className="mt-0.5 truncate text-[11px] font-semibold leading-tight opacity-95">{a.patient_name}</div><button type="button" onPointerDown={e=>beginResize(e,a)} className="absolute bottom-0 left-0 flex h-4 w-full cursor-ns-resize items-center justify-center bg-black/5 opacity-0 group-hover:opacity-100"><GripHorizontal size={13}/></button>
   </div>})}{p.loading&&<div className="absolute inset-0 z-30 animate-pulse bg-white/55"/>}</div>})}</div>
 </div></div>
 <Modal open={!!confirm} onClose={()=>!confirming&&setConfirm(null)} width={440} height="auto" maxHeight="calc(100vh - 48px)" closeOnOverlayClick={!confirming} showCloseButton={!confirming} panelClassName="p-6" zIndexClassName="z-[120]"><div className="pr-10"><div className="text-lg font-bold text-slate-950">{confirm?.title}</div><p className="mt-2 text-sm leading-relaxed text-slate-500">{confirm?.description}</p>{confirmError&&<div className="mt-4 rounded-xl border border-red/20 bg-red-soft px-3 py-2 text-sm font-semibold text-red">{confirmError}</div>}</div><div className="mt-6 flex justify-end gap-3"><button type="button" disabled={confirming} onClick={()=>setConfirm(null)} className="h-10 cursor-pointer rounded-xl border border-slate-200 px-4 text-sm font-bold text-slate-600 hover:bg-slate-50 disabled:opacity-50">Cancelar</button><button type="button" disabled={confirming} onClick={runConfirm} className={`flex h-10 cursor-pointer items-center gap-2 rounded-xl px-4 text-sm font-bold text-white disabled:opacity-60 ${confirm?.danger?"bg-red":"bg-brand"}`}>{confirming&&<LoaderCircle size={15} className="animate-spin"/>}{confirm?.confirmLabel}</button></div></Modal>
 </>}
function TimeAxis(){return <div className="relative border-r border-slate-200 bg-white" style={{height:CALENDAR_HEIGHT}}>{Array.from({length:END_HOUR-START_HOUR+1},(_,i)=>START_HOUR+i).map(h=><div key={h} className="absolute right-3 -translate-y-1/2 text-[11px] font-semibold text-slate-400" style={{top:(h-START_HOUR)*HOUR_HEIGHT}}>{String(h).padStart(2,"0")}:00</div>)}</div>}
function overlapIndex(a:CalendarAppointment,all:CalendarAppointment[]){const s=+new Date(a.starts_at),before=all.filter(x=>x.id!==a.id&&+new Date(x.starts_at)<=s&&+new Date(x.ends_at)>s),ordered=[...before,a].sort((x,y)=>+new Date(x.starts_at)-+new Date(y.starts_at)||x.id.localeCompare(y.id));return Math.min(ordered.findIndex(x=>x.id===a.id),5)}
function parts(v:string){return new Intl.DateTimeFormat("en-US",{timeZone:TZ,hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(v))}function minutes(v:string){const p=parts(v);return +(p.find(x=>x.type==="hour")?.value??0)*60+ +(p.find(x=>x.type==="minute")?.value??0)}function time(v:string){return new Intl.DateTimeFormat("pt-BR",{timeZone:TZ,hour:"2-digit",minute:"2-digit"}).format(new Date(v))}function dateKeyIso(v:string){return new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(v))}function minuteLabel(m:number){return `${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`}function build(d:Date,m:number){return new Date(`${formatLocalDateKey(d)}T${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}:00-03:00`).toISOString()}function dayLabel(d:Date){return new Intl.DateTimeFormat("pt-BR",{weekday:"short",day:"2-digit",month:"2-digit"}).format(d)}
export function formatLocalDateKey(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
