import assert from "node:assert/strict";
import { conversationAnalysisSchema } from "../lib/ai/conversationAnalysisSchema";
import { aggregatePatternSignals, appendPatternSection, validatePatternSignals } from "../lib/analysis/patternSignals";
const client = (id: string, text: string) => ({ id, text, sender_type: "client" });
const signal = (value: string, id: string, quote: string, category = "consultation_preference") => ({ category, value, label: "Preferência", confidence: 1, evidence: [{ message_id: id, quote }] });
const bh = client("bh", "Quero consulta depois das 17h.");
assert.equal(conversationAnalysisSchema.shape.pattern_signals.parse(undefined), null, "old in-flight batches remain unprocessed");
assert.deepEqual(conversationAnalysisSchema.shape.pattern_signals.parse([]), [], "processed without signals differs from legacy null");
const callback = client("call", "Não tem como ligar umas 17:30 a 18 horas?");
const rio = client("rio", "Vocês têm consulta sábado à tarde?");
const signals = validatePatternSignals([signal("from_17", bh.id, bh.text), signal("from_17", bh.id, bh.text)], [bh]);
assert.equal(signals.length, 1);
assert.deepEqual(signals[0].evidence_message_ids, [bh.id]);
assert.equal(validatePatternSignals([signal("from_17", callback.id, callback.text)], [callback]).length, 0);
assert.equal(validatePatternSignals([signal("from_17", callback.id, callback.text, "callback_preference")], [callback]).length, 1);
assert.equal(validatePatternSignals([signal("saturday_afternoon", rio.id, rio.text)], [rio]).length, 1);
const separate = [client("sat", "Pode ser sábado?"), client("afternoon", "Na segunda só à tarde.")];
assert.equal(validatePatternSignals([{ ...signal("saturday_afternoon", "sat", separate[0].text), evidence: separate.map(m => ({ message_id: m.id, quote: m.text })) }], separate).length, 0);
for (const raw of [signal("from_17", "missing", bh.text), signal("from_17", bh.id, "Consulta às 19h"), signal("from_17", bh.id, " "), { ...signal("from_17", bh.id, bh.text), confidence: 0.5 }])
    assert.equal(validatePatternSignals([raw], [bh]).length, 0);
assert.equal(validatePatternSignals([signal("from_17", bh.id, bh.text)], [{ ...bh, sender_type: "attendant" }]).length, 0);
const negative = client("no", "Não posso sábado à tarde.");
const earlier = client("early", "Consulta às 15h por favor.");
assert.equal(validatePatternSignals([signal("from_17", earlier.id, earlier.text)], [earlier]).length, 0);
assert.equal(validatePatternSignals([signal("saturday_afternoon", negative.id, negative.text)], [negative]).length, 0);
const friday = client("fri", "Quero consultar sexta de manhã.");
assert.equal(validatePatternSignals([signal("friday_morning", friday.id, friday.text)], [friday]).length, 1);
const rows = [{ conversation_id: "one", audience: "RA" as const, pattern_signals: signals }, { conversation_id: "two", audience: "Atendimento" as const, pattern_signals: signals }];
assert.deepEqual(aggregatePatternSignals([rows[0], rows[0]]), []);
const aggregates = aggregatePatternSignals([...rows, rows[0]]);
assert.equal(aggregates[0].conversations, 2);
assert.equal(aggregates[0].ra, 1);
assert.equal(aggregates[0].atendimento, 1);
const base = "## RA\nTexto\n\n## Atendimento\nTexto";
assert.equal(appendPatternSection(base, [], aggregates), base);
const report = appendPatternSection(base, [aggregates[0].key], aggregates);
assert.ok(report.indexOf("## Padrões encontrados") > report.indexOf("## Atendimento"));
assert.ok(report.includes("2 conversas distintas: 1 de RA e 1 de Atendimento"));
assert.throws(() => appendPatternSection(base, ["invented"], aggregates));
assert.deepEqual(aggregatePatternSignals([{ ...rows[0], pattern_signals: null }]), []);
console.log("Pattern evidence, deduplication, recurrence and report checks passed.");
