// components/inbox/SchedulingPanel.tsx
"use client";

import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { AlertCircle, CalendarCheck, CheckCircle2, Clock, Info, LoaderCircle, Search, Sparkles } from "lucide-react";
import FivAutomationBox from "@/components/scheduling/FivAutomationBox";
import SchedulingClientSummary from "@/components/scheduling/SchedulingClientSummary";
import { CalendarDatePicker } from "@/components/ui/CalendarDatePicker";
import { DetailsSidePanel } from "@/components/ui/DetailsSidePanel";
import { DropdownSelect, type DropdownSelectOption } from "@/components/ui/DropdownSelect";
import InfoTooltip from "@/components/ui/InfoTooltip";
import { getSchedulingProcedureOptions, SCHEDULING_DURATION_OPTIONS, SCHEDULING_TIME_OPTIONS } from "@/lib/scheduling/options";
import type { InboxChannel } from "@/types/inbox";
import type { CalendarAppointment, SchedulingAddressFields, SchedulingDataResponse, SchedulingForm, SchedulingFormat, SchedulingPersonFields } from "@/types/scheduling";

type Props = { open:boolean; threadId?:string|null; clientId?:string|null; onClose:()=>void; onOpenClientProfile?:(id:string)=>void; onCreated?:()=>void; selectClient?:boolean; client?:{name:string;phone:string|null;city:string|null;channel:InboxChannel}|null };
type Data = Omit<SchedulingDataResponse,"client"> & {client:SchedulingDataResponse["client"]|null};
type ClientOption={id:string;name:string|null;phone:string|null;email:string|null};
type ErrorMap=Record<string,string>;
const emptyPerson:SchedulingPersonFields={fullName:"",cpf:"",birthDate:"",email:"",phone:""};
const emptyAddress:SchedulingAddressFields={street:"",number:"",complement:"",neighborhood:"",city:"",state:"",cep:"",country:""};
const initialForm:SchedulingForm={unitId:"",doctorId:"",schedulingDate:"",schedulingTime:"",durationMinutes:45,procedureName:"Consulta",primary:{...emptyPerson},spouse:{...emptyPerson},address:{...emptyAddress},notes:""};

export default function SchedulingPanel({open,threadId,clientId,onClose,onOpenClientProfile,onCreated,selectClient=false,client=null}:Props){
 const [format,setFormat]=useState<SchedulingFormat>("congelamento"); const [form,setForm]=useState(initialForm); const [data,setData]=useState<Data|null>(null);
 const [errors,setErrors]=useState<ErrorMap>({}); const [loading,setLoading]=useState(false); const [autofilling,setAutofilling]=useState(false); const [submitting,setSubmitting]=useState(false);
 const [message,setMessage]=useState<{type:"error"|"success";text:string}|null>(null); const [clients,setClients]=useState<ClientOption[]>([]); const [selectedClientId,setSelectedClientId]=useState(""); const [clientQuery,setClientQuery]=useState(""); const [loadingClients,setLoadingClients]=useState(false); const requestRef=useRef(0);
 const [busy,setBusy]=useState<CalendarAppointment[]>([]); const [loadingBusy,setLoadingBusy]=useState(false); const [addToFivFunnel,setAddToFivFunnel]=useState(true);

 useEffect(()=>{if(open)setAddToFivFunnel(true)},[open]);
 useEffect(()=>{if(!open)return; const c=new AbortController(); setLoading(true); setMessage(null); setErrors({});
  (async()=>{try{const r=await fetch(threadId?`/api/inbox/scheduling-data?thread_id=${encodeURIComponent(threadId)}`:"/api/scheduling/options",{cache:"no-store",signal:c.signal}); const j=await r.json(); if(!r.ok)throw new Error(j?.error??"Não foi possível carregar os dados.");
   if(threadId){setData(j);setFormat(j.suggestedFormat);setForm(j.form)}else{setData({client:null,spouse:null,units:j.units??[],doctors:j.doctors??[],suggestedFormat:"congelamento",form:initialForm});setFormat("congelamento");setForm(initialForm);if(selectClient){setSelectedClientId("");setClientQuery("")}}
  }catch(e){if(!c.signal.aborted)setMessage({type:"error",text:e instanceof Error?e.message:"Não foi possível carregar os dados."})}finally{if(!c.signal.aborted)setLoading(false)}})(); return()=>c.abort();
 },[open,threadId,selectClient]);
 useEffect(()=>{if(!open||!selectClient)return; const c=new AbortController();setLoadingClients(true);(async()=>{try{const r=await fetch("/api/clientes",{cache:"no-store",signal:c.signal});const j=await r.json();if(!r.ok)throw new Error(j?.error);setClients(j.clients??[])}catch{if(!c.signal.aborted)setClients([])}finally{if(!c.signal.aborted)setLoadingClients(false)}})();return()=>c.abort()},[open,selectClient]);
 useEffect(()=>{const date=toDateInput(form.schedulingDate);if(!open||!date||!form.doctorId){setBusy([]);return} const c=new AbortController(); setLoadingBusy(true); const end=addDay(date);
  (async()=>{try{const q=new URLSearchParams({start:date,end});q.append("doctor_ids",form.doctorId);q.append("statuses","scheduled");q.append("statuses","confirmed");const r=await fetch(`/api/scheduling/appointments?${q}`,{cache:"no-store",signal:c.signal});const j=await r.json();if(!r.ok)throw new Error();setBusy(j.appointments??[])}catch{if(!c.signal.aborted)setBusy([])}finally{if(!c.signal.aborted)setLoadingBusy(false)}})();return()=>c.abort()
 },[open,form.schedulingDate,form.doctorId]);

 const profileClientId=data?.client?.id??clientId??null; const availableDoctors=(data?.doctors??[]).filter(d=>d.unit_id===form.unitId); const disabled=loading||autofilling||submitting;
 const visibleClients=clients.filter(c=>`${c.name??""} ${c.phone??""}`.toLowerCase().includes(clientQuery.toLowerCase())).slice(0,10);
 const timeOptions=useMemo<DropdownSelectOption[]>(()=>SCHEDULING_TIME_OPTIONS.map(o=>{const overlap=isBusy(o.value,form.schedulingDate,form.durationMinutes,busy);return {...o,disabled:overlap,strikethrough:overlap,description:overlap?"Ocupado":undefined}}),[busy,form.schedulingDate,form.durationMinutes]);
 function clear(field?:string){setMessage(null);if(field)setErrors(x=>{const n={...x};delete n[field];return n})}
 function updatePerson(w:"primary"|"spouse",k:keyof SchedulingPersonFields,v:string){setForm(f=>({...f,[w]:{...f[w],[k]:formatValue(k,v)}}));clear(`${w}.${String(k)}`)}
 function updateAddress(k:keyof SchedulingAddressFields,v:string){setForm(f=>({...f,address:{...f.address,[k]:k==="cep"?formatCep(v):v}}));clear(`address.${String(k)}`)}
 function update<K extends keyof SchedulingForm>(k:K,v:SchedulingForm[K]){setForm(f=>({...f,[k]:v}));clear(String(k))}
 function selectUnit(id:string){setForm(f=>{const u=data?.units.find(x=>x.id===id);return {...f,unitId:id,doctorId:(data?.doctors??[]).some(d=>d.id===f.doctorId&&d.unit_id===id)?f.doctorId:"",address:{...f.address,state:f.address.state.trim()||u?.state?.trim()||"",country:f.address.country.trim()||"Brasil"}}});clear("unitId")}
 async function chooseClient(id:string){const req=++requestRef.current;setSelectedClientId(id);if(!id)return;setLoading(true);try{const r=await fetch(`/api/inbox/scheduling-data?client_id=${encodeURIComponent(id)}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.error);if(req!==requestRef.current)return;setData(j);setFormat(j.suggestedFormat);setForm(j.form)}catch(e){setMessage({type:"error",text:e instanceof Error?e.message:"Não foi possível carregar o cliente."})}finally{if(req===requestRef.current)setLoading(false)}}
 async function autofill(){if(!threadId)return;setAutofilling(true);clear();try{const r=await fetch("/api/inbox/scheduling-autofill",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({threadId,format,form})});const j=await r.json();if(!r.ok)throw new Error(j?.error);setForm(j.form);setMessage({type:"success",text:"Dados preenchidos automaticamente."})}catch(e){setMessage({type:"error",text:e instanceof Error?e.message:"Não foi possível preencher os dados."})}finally{setAutofilling(false)}}
 async function submit(){if(submitting)return;const next=validate(form,format);if(selectClient&&!profileClientId)next.clientId="Selecione um cliente.";setErrors(next);setMessage(null);if(Object.keys(next).length)return;const startsAt=toBrazilIso(form.schedulingDate,form.schedulingTime);if(!startsAt)return;
  setSubmitting(true);try{const r=await fetch("/api/scheduling/appointments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({threadId,clientId:profileClientId,unitId:form.unitId,doctorId:form.doctorId,startsAt,durationMinutes:form.durationMinutes,status:"scheduled",format,procedureName:form.procedureName,primary:form.primary,spouse:form.spouse,address:form.address,notes:form.notes,addToFivFunnel})});const j=await r.json();if(!r.ok)throw new Error(j?.issues?.[0]?.message??j?.error??"Não foi possível criar o agendamento.");setMessage({type:"success",text:"Agendamento criado com sucesso."});window.dispatchEvent(new Event("appointments:changed"));onCreated?.()}catch(e){setMessage({type:"error",text:e instanceof Error?e.message:"Não foi possível criar o agendamento."})}finally{setSubmitting(false)}}

 const clientName=data?.client?.name??client?.name??"Cliente sem nome"; const clientPhone=data?.client?.phone??client?.phone??"Sem telefone"; const clientCity=data?.client?.city??client?.city??null;
 return <DetailsSidePanel open={open} title="Agendar" onClose={onClose} headerContent={(profileClientId||client)?<SchedulingClientSummary name={clientName} phone={clientPhone} city={clientCity} onClick={profileClientId&&onOpenClientProfile?()=>onOpenClientProfile(profileClientId):undefined}/>:undefined} bodyClassName="min-h-0 flex-1 overflow-y-auto px-6 py-6 pt-3">
  <div className={`space-y-6 ${loading?"pointer-events-none opacity-45":""}`}>
   {selectClient&&<Field label="Cliente" error={errors.clientId}><DropdownSelect value={selectedClientId} onChange={chooseClient} options={visibleClients.map(c=>({value:c.id,label:c.name?.trim()||"Cliente sem nome",description:c.phone??"Sem telefone"}))} searchable searchValue={clientQuery} onSearchChange={setClientQuery} searchPlaceholder={loadingClients?"Carregando clientes...":"Digite nome ou telefone"} icon={<Search size={16}/>} loading={loadingClients} widthClassName="w-full" dropdownWidthClassName="w-full"/></Field>}
   {!selectClient&&<div className="flex items-center gap-2"><button type="button" onClick={autofill} disabled={disabled||!threadId} className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold text-slate-700 shadow-sm transition hover:bg-selection disabled:opacity-55">{autofilling?<LoaderCircle size={16} className="animate-spin text-brand"/>:<Sparkles size={16} className="text-brand"/>}{autofilling?"Preenchendo...":"Autopreencher"}</button><InfoTooltip text="Preenche os dados e sugere a unidade mais compatível com o endereço informado no chat."><button type="button" className="flex h-9 w-9 cursor-help items-center justify-center rounded-xl text-slate-400 hover:bg-slate-100 hover:text-slate-700"><Info size={17}/></button></InfoTooltip></div>}
   <div className="grid grid-cols-[.75fr_1.25fr] gap-3"><Select label="Unidade" value={form.unitId} onChange={selectUnit} options={(data?.units??[]).map(x=>({value:x.id,label:x.name}))} error={errors.unitId} disabled={disabled}/><Select label="Médico" value={form.doctorId} onChange={v=>update("doctorId",v)} options={availableDoctors.map(x=>({value:x.id,label:x.name}))} error={errors.doctorId} disabled={disabled||!form.unitId}/></div>
   <div className="grid grid-cols-[.75fr_1.25fr] gap-3"><Select label="Duração" value={String(form.durationMinutes)} onChange={v=>update("durationMinutes",Number(v))} options={SCHEDULING_DURATION_OPTIONS}/><Select label="Procedimento" value={form.procedureName} onChange={v=>update("procedureName",v)} options={getSchedulingProcedureOptions(form.procedureName)} error={errors.procedureName}/></div>
   <section><div className="mb-3 text-xs font-bold uppercase tracking-wide text-slate-500">Formato do agendamento</div><div className="flex gap-5"><Radio active={format==="congelamento"} label="Congelamento" onClick={()=>setFormat("congelamento")}/><Radio active={format==="casal"} label="Casal" onClick={()=>setFormat("casal")}/></div></section>
   <div className="grid grid-cols-[1.2fr_.8fr] gap-3"><Field label="Data" error={errors.schedulingDate}><CalendarDatePicker value={toDateInput(form.schedulingDate)} onChange={v=>update("schedulingDate",fromDateInput(v))} invalid={!!errors.schedulingDate}/></Field><Select label="Horário" value={form.schedulingTime} onChange={v=>update("schedulingTime",v)} options={timeOptions} error={errors.schedulingTime} loading={loadingBusy} icon={<Clock size={16} className="cursor-pointer text-slate-400 hover:text-slate-700"/>}/></div>
   <h3 className="pt-1 text-sm font-bold uppercase tracking-wide text-slate-950">DETALHES DO CLIENTE</h3>
   <Person values={form.primary} who="primary" errors={errors} onChange={updatePerson}/>{format==="casal"&&<Person title="Cônjuge" values={form.spouse} who="spouse" errors={errors} onChange={updatePerson}/>}<Address values={form.address} errors={errors} onChange={updateAddress}/>
   <Text label="Observações" value={form.notes} onChange={v=>update("notes",v)} multiline/>
   {isInitialProcedure(form.procedureName)&&<FivAutomationBox checked={addToFivFunnel} onChange={setAddToFivFunnel} disabled={disabled}/>} {message&&<Notice {...message}/>}<button type="button" disabled={disabled||message?.type==="success"} onClick={submit} className="flex h-11 w-full cursor-pointer items-center justify-center gap-2 rounded-xl bg-brand px-5 text-sm font-bold text-white shadow-sm hover:bg-brand/90 disabled:opacity-55">{submitting?<LoaderCircle size={17} className="animate-spin"/>:<CalendarCheck size={17}/>} {submitting?"Criando...":"Criar agendamento"}</button>
  </div>
 </DetailsSidePanel>
}

function Field({label,error,children}:{label:string;error?:string;children:ReactNode}){return <div><span className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">{label}</span>{children}{error&&<span className="mt-1.5 block text-xs font-medium text-red">{error}</span>}</div>}
function Select({label,value,onChange,options,error,disabled,icon,loading}:{label:string;value:string;onChange:(v:string)=>void;options:DropdownSelectOption[];error?:string;disabled?:boolean;icon?:ReactNode;loading?:boolean}){return <Field label={label} error={error}><DropdownSelect value={value} onChange={onChange} options={options} placeholder="Selecione" disabled={disabled} invalid={!!error} icon={icon} loading={loading} loadingLabel="Verificando horários..." widthClassName="w-full" dropdownWidthClassName="w-full"/></Field>}
function Text({label,value,onChange,error,optional,multiline,placeholder,inputMode,type="text"}:{label:string;value:string;onChange:(v:string)=>void;error?:string;optional?:boolean;multiline?:boolean;placeholder?:string;inputMode?:"numeric"|"text"|"email";type?:string}){const c=`w-full rounded-xl border bg-white px-3 text-sm outline-none placeholder:text-slate-400 ${error?"border-red":"border-slate-200 focus:border-brand"}`;return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">{label}{optional&&<span className="ml-1 font-medium normal-case text-slate-400">(opcional)</span>}</span>{multiline?<textarea rows={3} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className={`${c} min-h-[72px] resize-none py-2.5`}/>:<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} inputMode={inputMode} type={type} className={`${c} h-11`}/>} {error&&<span className="mt-1.5 block text-xs font-medium text-red">{error}</span>}</label>}
function Person({title,values,who,errors,onChange}:{title?:string;values:SchedulingPersonFields;who:"primary"|"spouse";errors:ErrorMap;onChange:(w:"primary"|"spouse",k:keyof SchedulingPersonFields,v:string)=>void}){return <section className="space-y-4">{title&&<h3 className="text-sm font-bold text-slate-950">{title}</h3>}<Text label="Nome completo (sem abreviações)" value={values.fullName} onChange={v=>onChange(who,"fullName",v)} error={errors[`${who}.fullName`]} placeholder="Nome e sobrenome"/><div className="grid grid-cols-2 gap-3"><Text label="CPF" value={values.cpf} onChange={v=>onChange(who,"cpf",v)} error={errors[`${who}.cpf`]} placeholder="000.000.000-00" inputMode="numeric"/><Text label="Data de nascimento" value={values.birthDate} onChange={v=>onChange(who,"birthDate",v)} error={errors[`${who}.birthDate`]} placeholder="DD/MM/AAAA" inputMode="numeric"/></div><div className="grid grid-cols-2 gap-3"><Text label="E-mail" value={values.email} onChange={v=>onChange(who,"email",v)} error={errors[`${who}.email`]} placeholder="nome@exemplo.com" inputMode="email" type="email"/><Text label="Telefone" value={values.phone} onChange={v=>onChange(who,"phone",v)} error={errors[`${who}.phone`]} placeholder="(00) 00000-0000" inputMode="numeric"/></div></section>}
function Address({values,errors,onChange}:{values:SchedulingAddressFields;errors:ErrorMap;onChange:(k:keyof SchedulingAddressFields,v:string)=>void}){return <section className="space-y-4"><div className="grid grid-cols-[.8fr_1.2fr] gap-3"><Text label="CEP" value={values.cep} onChange={v=>onChange("cep",v)} error={errors["address.cep"]} placeholder="00000-000" inputMode="numeric"/><Text label="Rua" value={values.street} onChange={v=>onChange("street",v)} error={errors["address.street"]} placeholder="Nome da rua"/></div><div className="grid grid-cols-[.7fr_1.3fr] gap-3"><Text label="Número" value={values.number} onChange={v=>onChange("number",v)} error={errors["address.number"]} placeholder="Número"/><Text label="Complemento" optional value={values.complement} onChange={v=>onChange("complement",v)} placeholder="Apto, bloco..."/></div><div className="grid grid-cols-2 gap-3"><Text label="Bairro" optional value={values.neighborhood} onChange={v=>onChange("neighborhood",v)} placeholder="Bairro"/><Text label="Cidade" value={values.city} onChange={v=>onChange("city",v)} error={errors["address.city"]} placeholder="Cidade"/></div><div className="grid grid-cols-2 gap-3"><Text label="Estado" value={values.state} onChange={v=>onChange("state",v)} error={errors["address.state"]} placeholder="UF"/><Text label="País" value={values.country} onChange={v=>onChange("country",v)} placeholder="Brasil"/></div></section>}
function Radio({active,label,onClick}:{active:boolean;label:string;onClick:()=>void}){return <button type="button" onClick={onClick} className="flex cursor-pointer items-center gap-2 text-sm font-semibold text-slate-700"><span className={`flex h-5 w-5 items-center justify-center rounded-full border ${active?"border-brand":"border-slate-300"}`}><span className={`h-2.5 w-2.5 rounded-full bg-brand ${active?"scale-100":"scale-0"}`}/></span>{label}</button>}
function Notice({type,text}:{type:"error"|"success";text:string}){return <div className={`flex items-start gap-2 rounded-xl border px-4 py-3 text-sm font-semibold ${type==="error"?"border-red/20 bg-red-soft text-red":"border-green/20 bg-green-soft text-green"}`}>{type==="error"?<AlertCircle size={16}/>:<CheckCircle2 size={16}/>} {text}</div>}
function isInitialProcedure(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLocaleLowerCase("pt-BR").replace(/\s+/g," ")==="consulta inicial"}
function validate(f:SchedulingForm,format:SchedulingFormat){const e:ErrorMap={};if(!f.unitId)e.unitId="Selecione uma unidade.";if(!f.doctorId)e.doctorId="Selecione um médico.";if(!isDate(f.schedulingDate))e.schedulingDate="Informe uma data válida.";if(!/^\d{2}:\d{2}$/.test(f.schedulingTime))e.schedulingTime="Selecione um horário.";if(!f.procedureName.trim())e.procedureName="Informe o procedimento.";person(f.primary,"primary",e);if(format==="casal")person(f.spouse,"spouse",e);if(!f.address.street.trim())e["address.street"]="Informe a rua.";if(!f.address.number.trim())e["address.number"]="Informe o número.";if(!f.address.city.trim())e["address.city"]="Informe a cidade.";if(!f.address.state.trim())e["address.state"]="Informe o estado.";if(only(f.address.cep).length!==8)e["address.cep"]="Informe um CEP válido.";return e}
function person(p:SchedulingPersonFields,k:string,e:ErrorMap){if(p.fullName.trim().split(/\s+/).length<2)e[`${k}.fullName`]="Informe o nome completo.";if(only(p.cpf).length!==11)e[`${k}.cpf`]="Informe um CPF válido.";if(!isDate(p.birthDate))e[`${k}.birthDate`]="Informe uma data válida.";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email))e[`${k}.email`]="Informe um e-mail válido.";if(only(p.phone).length<10)e[`${k}.phone`]="Informe um telefone válido."}
function formatValue(k:keyof SchedulingPersonFields,v:string){if(k==="cpf")return only(v).slice(0,11).replace(/^(\d{3})(\d)/,"$1.$2").replace(/^(\d{3})\.(\d{3})(\d)/,"$1.$2.$3").replace(/\.(\d{3})(\d)/,".$1-$2");if(k==="birthDate")return only(v).slice(0,8).replace(/^(\d{2})(\d)/,"$1/$2").replace(/^(\d{2})\/(\d{2})(\d)/,"$1/$2/$3");if(k==="phone")return only(v).replace(/^55/,"").slice(0,11).replace(/^(\d{2})(\d)/,"($1) $2").replace(/(\d{5})(\d)/,"$1-$2");return k==="email"?v.trimStart().toLowerCase():v}
function formatCep(v:string){return only(v).slice(0,8).replace(/^(\d{5})(\d)/,"$1-$2")} function only(v:string){return v.replace(/\D/g,"")} function isDate(v:string){const m=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(v);if(!m)return false;const d=new Date(+m[3],+m[2]-1,+m[1]);return d.getFullYear()===+m[3]&&d.getMonth()===+m[2]-1&&d.getDate()===+m[1]}
function toDateInput(v:string){const m=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(v);return m?`${m[3]}-${m[2]}-${m[1]}`:""} function fromDateInput(v:string){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(v);return m?`${m[3]}/${m[2]}/${m[1]}`:""} function addDay(v:string){const d=new Date(`${v}T12:00:00`);d.setDate(d.getDate()+1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function toBrazilIso(d:string,t:string){const x=toDateInput(d);if(!x||!t)return null;return new Date(`${x}T${t}:00-03:00`).toISOString()} function isBusy(t:string,d:string,duration:number,a:CalendarAppointment[]){const date=toDateInput(d);if(!date)return false;const s=new Date(`${date}T${t}:00-03:00`).getTime(),e=s+duration*60000;return a.some(x=>s<new Date(x.ends_at).getTime()&&e>new Date(x.starts_at).getTime())}
